### ISSUE TITLE
No timestamp field in ROS2 PointCloud2 message

### ISSUE THREAD

**Issue by Marselka** [RoboSense-LiDAR/rs_driver#65]
We use FastLIO-like Lidar-Inertial Odometry algorithm that **needs the timestamp of every point** in the lidar pointcloud.

This requirement is satisfied at least by **Velodyne VLP-16** and **Livox MID360** lidar models. However, the combo of **Robosense Airy** + ROS2 rs_driver cannot provide timestamp field. 
`ros2 topic echo /rlidar_points`:

```
header:
  stamp:
    sec: 668
    nanosec: 403185160
  frame_id: base_scan
height: 900
width: 96
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 12
  datatype: 7
  count: 1
is_bigendian: false
point_step: 16
row_step: 1536
data:
- 41
- 169
- 139
...
```

Is it possible to add timestamp field to the PointCloud2 ROS2 message in the driver?
